/*
    http://www.codeslinger.co.uk/pages/projects/mastersystem.html

    Copyright(c) 2008 < copyright holders > (sic)
    Modified 2021 Matt Marchant https://github.com/fallahn

    This software is provided 'as-is', without any express or implied
    warranty.In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter itand redistribute it
    freely, subject to the following restrictions :

    1. The origin of this software must not be misrepresented; you must not
    claim that you wrote the original software.If you use this software
    in a product, an acknowledgment in the product documentation would be
    appreciated but is not required.

    2. Altered source versions must be plainly marked as such, and must not be
    misrepresented as being the original software.

    3. This notice may not be removed or altered from any source distribution.
*/

#pragma once

static const char* Z80MNEMONICSFD[]=
{
    "ADD IY,BC",
    "ADD IY,DE",
    "LD IY,nn",
    "LD (nn),IY",
    "INC IY",
    "INC IYH",
    "DEC IYH",
    "LD IYH,n",
    "ADD IY,IY",
    "LD IY,(nn)",
    "DEC IY",
    "INC IYL",
    "DEC IYL",
    "LD IYL,n",
    "INC (IY+d)",
    "DEC (IY+d)",
    "LD (IY+d),n",
    "ADD IY,SP",
    "LD B,IYH",
    "LD B,IYL",
    "LD B,(IY+d)",
    "LD C,IYH",
    "LD C,IYL",
    "LD C,(IY+d)",
    "LD D,IYH",
    "LD D,IYL",
    "LD D,(IY+d)",
    "LD E,IYH",
    "LD E,IYL",
    "LD E,(IY+d)",
    "LD IYH,B",
    "LD IYH,C",
    "LD IYH,D",
    "LD IYH,E",
    "LD IYH,IYH",
    "LD IYH,IYL",
    "LD H,(IY+d)",
    "LD IYH,A",
    "LD IYL,B",
    "LD IYL,C",
    "LD IYL,D",
    "LD IYL,E",
    "LD IYL,IYH",
    "LD IYL,IYL",
    "LD L,(IY+d)",
    "LD IYL,A",
    "LD (IY+d),B",
    "LD (IY+d),C",
    "LD (IY+d),D",
    "LD (IY+d),E",
    "LD (IY+d),H",
    "LD (IY+d),L",
    "LD (IY+d),A",
    "LD A,IYH",
    "LD A,IYL",
    "LD A,(IY+d)",
    "ADD A,IYH",
    "ADD A,IYL",
    "ADD A,(IY+d)",
    "ADC A,IYH",
    "ADC A,IYL",
    "ADC A,(IY+d)",
    "SUB IYH",
    "SUB IYL",
    "SUB (IY+d)",
    "SBC A,IYH",
    "SBC A,IYL",
    "SBC A,(IY+d)",
    "AND IYH",
    "AND IYL",
    "AND (IY+d)",
    "XOR IYH",
    "XOR IYL",
    "XOR (IY+d)",
    "OR IYH",
    "OR IYL",
    "OR (IY+d)",
    "CP IYH",
    "CP IYL",
    "CP (IY+d)",
    "LD B,RLC (IY+d)",
    "LD C,RLC (IY+d)",
    "LD D,RLC (IY+d)",
    "LD E,RLC (IY+d)",
    "LD H,RLC (IY+d)",
    "LD L,RLC (IY+d)",
    "RLC (IY+d)",
    "LD A,RLC (IY+d)",
    "LD B,RRC (IY+d)",
    "LD C,RRC (IY+d)",
    "LD D,RRC (IY+d)",
    "LD E,RRC (IY+d)",
    "LD H,RRC (IY+d)",
    "LD L,RRC (IY+d)",
    "RRC (IY+d)",
    "LD A,RRC (IY+d)",
    "LD B,RL (IY+d)",
    "LD C,RL (IY+d)",
    "LD D,RL (IY+d)",
    "LD E,RL (IY+d)",
    "LD H,RL (IY+d)",
    "LD L,RL (IY+d)",
    "RL (IY+d)",
    "LD A,RL (IY+d)",
    "LD B,RR (IY+d)",
    "LD C,RR (IY+d)",
    "LD D,RR (IY+d)",
    "LD E,RR (IY+d)",
    "LD H,RR (IY+d)",
    "LD L,RR (IY+d)",
    "RR (IY+d)",
    "LD A,RR (IY+d)",
    "LD B,SLA (IY+d)",
    "LD C,SLA (IY+d)",
    "LD D,SLA (IY+d)",
    "LD E,SLA (IY+d)",
    "LD H,SLA (IY+d)",
    "LD L,SLA (IY+d)",
    "SLA (IY+d)",
    "LD A,SLA (IY+d)",
    "LD B,SRA (IY+d)",
    "LD C,SRA (IY+d)",
    "LD D,SRA (IY+d)",
    "LD E,SRA (IY+d)",
    "LD H,SRA (IY+d)",
    "LD L,SRA (IY+d)",
    "SRA (IY+d)",
    "LD A,SRA (IY+d)",
    "LD B,SLL (IY+d)",
    "LD C,SLL (IY+d)",
    "LD D,SLL (IY+d)",
    "LD E,SLL (IY+d)",
    "LD H,SLL (IY+d)",
    "LD L,SLL (IY+d)",
    "SLL (IY+d)",
    "LD A,SLL (IY+d)",
    "LD B,SRL (IY+d)",
    "LD C,SRL (IY+d)",
    "LD D,SRL (IY+d)",
    "LD E,SRL (IY+d)",
    "LD H,SRL (IY+d)",
    "LD L,SRL (IY+d)",
    "SRL (IY+d)",
    "LD A,SRL (IY+d)",
    "BIT 0,(IY+d)",
    "BIT 0,(IY+d)",
    "BIT 0,(IY+d)",
    "BIT 0,(IY+d)",
    "BIT 0,(IY+d)",
    "BIT 0,(IY+d)",
    "BIT 0,(IY+d)",
    "BIT 0,(IY+d)",
    "BIT 1,(IY+d)",
    "BIT 1,(IY+d)",
    "BIT 1,(IY+d)",
    "BIT 1,(IY+d)",
    "BIT 1,(IY+d)",
    "BIT 1,(IY+d)",
    "BIT 1,(IY+d)",
    "BIT 1,(IY+d)",
    "BIT 2,(IY+d)",
    "BIT 2,(IY+d)",
    "BIT 2,(IY+d)",
    "BIT 2,(IY+d)",
    "BIT 2,(IY+d)",
    "BIT 2,(IY+d)",
    "BIT 2,(IY+d)",
    "BIT 2,(IY+d)",
    "BIT 3,(IY+d)",
    "BIT 3,(IY+d)",
    "BIT 3,(IY+d)",
    "BIT 3,(IY+d)",
    "BIT 3,(IY+d)",
    "BIT 3,(IY+d)",
    "BIT 3,(IY+d)",
    "BIT 3,(IY+d)",
    "BIT 4,(IY+d)",
    "BIT 4,(IY+d)",
    "BIT 4,(IY+d)",
    "BIT 4,(IY+d)",
    "BIT 4,(IY+d)",
    "BIT 4,(IY+d)",
    "BIT 4,(IY+d)",
    "BIT 4,(IY+d)",
    "BIT 5,(IY+d)",
    "BIT 5,(IY+d)",
    "BIT 5,(IY+d)",
    "BIT 5,(IY+d)",
    "BIT 5,(IY+d)",
    "BIT 5,(IY+d)",
    "BIT 5,(IY+d)",
    "BIT 5,(IY+d)",
    "BIT 6,(IY+d)",
    "BIT 6,(IY+d)",
    "BIT 6,(IY+d)",
    "BIT 6,(IY+d)",
    "BIT 6,(IY+d)",
    "BIT 6,(IY+d)",
    "BIT 6,(IY+d)",
    "BIT 6,(IY+d)",
    "BIT 7,(IY+d)",
    "BIT 7,(IY+d)",
    "BIT 7,(IY+d)",
    "BIT 7,(IY+d)",
    "BIT 7,(IY+d)",
    "BIT 7,(IY+d)",
    "BIT 7,(IY+d)",
    "BIT 7,(IY+d)",
    "LD B,RES 0,(IY+d)",
    "LD C,RES 0,(IY+d)",
    "LD D,RES 0,(IY+d)",
    "LD E,RES 0,(IY+d)",
    "LD H,RES 0,(IY+d)",
    "LD L,RES 0,(IY+d)",
    "RES 0,(IY+d)",
    "LD A,RES 0,(IY+d)",
    "LD B,RES 1,(IY+d)",
    "LD C,RES 1,(IY+d)",
    "LD D,RES 1,(IY+d)",
    "LD E,RES 1,(IY+d)",
    "LD H,RES 1,(IY+d)",
    "LD L,RES 1,(IY+d)",
    "RES 1,(IY+d)",
    "LD A,RES 1,(IY+d)",
    "LD B,RES 2,(IY+d)",
    "LD C,RES 2,(IY+d)",
    "LD D,RES 2,(IY+d)",
    "LD E,RES 2,(IY+d)",
    "LD H,RES 2,(IY+d)",
    "LD L,RES 2,(IY+d)",
    "RES 2,(IY+d)",
    "LD A,RES 2,(IY+d)",
    "LD B,RES 3,(IY+d)",
    "LD C,RES 3,(IY+d)",
    "LD D,RES 3,(IY+d)",
    "LD E,RES 3,(IY+d)",
    "LD H,RES 3,(IY+d)",
    "LD L,RES 3,(IY+d)",
    "RES 3,(IY+d)",
    "LD A,RES 3,(IY+d)",
    "LD B,RES 4,(IY+d)",
    "LD C,RES 4,(IY+d)",
    "LD D,RES 4,(IY+d)",
    "LD E,RES 4,(IY+d)",
    "LD H,RES 4,(IY+d)",
    "LD L,RES 4,(IY+d)",
    "RES 4,(IY+d)",
    "LD A,RES 4,(IY+d)",
    "LD B,RES 5,(IY+d)",
    "LD C,RES 5,(IY+d)",
    "LD D,RES 5,(IY+d)",
    "LD E,RES 5,(IY+d)",
    "LD H,RES 5,(IY+d)",
    "LD L,RES 5,(IY+d)",
    "RES 5,(IY+d)",
    "LD A,RES 5,(IY+d)",
    "LD B,RES 6,(IY+d)",
    "LD C,RES 6,(IY+d)",
    "LD D,RES 6,(IY+d)",
    "LD E,RES 6,(IY+d)",
    "LD H,RES 6,(IY+d)",
    "LD L,RES 6,(IY+d)",
    "RES 6,(IY+d)",
    "LD A,RES 6,(IY+d)",
    "LD B,RES 7,(IY+d)",
    "LD C,RES 7,(IY+d)",
    "LD D,RES 7,(IY+d)",
    "LD E,RES 7,(IY+d)",
    "LD H,RES 7,(IY+d)",
    "LD L,RES 7,(IY+d)",
    "RES 7,(IY+d)",
    "LD A,RES 7,(IY+d)",
    "LD B,SET 0,(IY+d)",
    "LD C,SET 0,(IY+d)",
    "LD D,SET 0,(IY+d)",
    "LD E,SET 0,(IY+d)",
    "LD H,SET 0,(IY+d)",
    "LD L,SET 0,(IY+d)",
    "SET 0,(IY+d)",
    "LD A,SET 0,(IY+d)",
    "LD B,SET 1,(IY+d)",
    "LD C,SET 1,(IY+d)",
    "LD D,SET 1,(IY+d)",
    "LD E,SET 1,(IY+d)",
    "LD H,SET 1,(IY+d)",
    "LD L,SET 1,(IY+d)",
    "SET 1,(IY+d)",
    "LD A,SET 1,(IY+d)",
    "LD B,SET 2,(IY+d)",
    "LD C,SET 2,(IY+d)",
    "LD D,SET 2,(IY+d)",
    "LD E,SET 2,(IY+d)",
    "LD H,SET 2,(IY+d)",
    "LD L,SET 2,(IY+d)",
    "SET 2,(IY+d)",
    "LD A,SET 2,(IY+d)",
    "LD B,SET 3,(IY+d)",
    "LD C,SET 3,(IY+d)",
    "LD D,SET 3,(IY+d)",
    "LD E,SET 3,(IY+d)",
    "LD H,SET 3,(IY+d)",
    "LD L,SET 3,(IY+d)",
    "SET 3,(IY+d)",
    "LD A,SET 3,(IY+d)",
    "LD B,SET 4,(IY+d)",
    "LD C,SET 4,(IY+d)",
    "LD D,SET 4,(IY+d)",
    "LD E,SET 4,(IY+d)",
    "LD H,SET 4,(IY+d)",
    "LD L,SET 4,(IY+d)",
    "SET 4,(IY+d)",
    "LD A,SET 4,(IY+d)",
    "LD B,SET 5,(IY+d)",
    "LD C,SET 5,(IY+d)",
    "LD D,SET 5,(IY+d)",
    "LD E,SET 5,(IY+d)",
    "LD H,SET 5,(IY+d)",
    "LD L,SET 5,(IY+d)",
    "SET 5,(IY+d)",
    "LD A,SET 5,(IY+d)",
    "LD B,SET 6,(IY+d)",
    "LD C,SET 6,(IY+d)",
    "LD D,SET 6,(IY+d)",
    "LD E,SET 6,(IY+d)",
    "LD H,SET 6,(IY+d)",
    "LD L,SET 6,(IY+d)",
    "SET 6,(IY+d)",
    "LD A,SET 6,(IY+d)",
    "LD B,SET 7,(IY+d)",
    "LD C,SET 7,(IY+d)",
    "LD D,SET 7,(IY+d)",
    "LD E,SET 7,(IY+d)",
    "LD H,SET 7,(IY+d)",
    "LD L,SET 7,(IY+d)",
    "SET 7,(IY+d)",
    "LD A,SET 7,(IY+d)",
};

static const char* Z80MNEMONICSDE[]=
{
    "IN B,(C)",
    "OUT (C),B",
    "SBC HL,BC",
    "LD (nn),BC",
    "NEG",
    "RETN",
    "IM 0",
    "LD I,A",
    "IN C,(C)",
    "OUT (C),C",
    "ADC HL,BC",
    "LD BC,(nn)",
    "NEG",
    "RETI",
    "IM 0",
    "LD R,A",
    "IN D,(C)",
    "OUT (C),D",
    "SBC HL,DE",
    "LD (nn),DE",
    "NEG",
    "RETN",
    "IM 1",
    "LD A,I",
    "IN E,(C)",
    "OUT (C),E",
    "ADC HL,DE",
    "LD DE,(nn)",
    "NEG",
    "RETN",
    "IM 2",
    "LD A,R",
    "IN H,(C)",
    "OUT (C),H",
    "SBC HL,HL",
    "LD (nn),HL",
    "NEG",
    "RETN",
    "IM 0",
    "RRD",
    "IN L,(C)",
    "OUT (C),L",
    "ADC HL,HL",
    "LD HL,(nn)",
    "NEG",
    "RETN",
    "IM 0",
    "RLD",
    "IN F,(C) / IN (C)",
    "OUT (C),0",
    "SBC HL,SP",
    "LD (nn),SP",
    "NEG",
    "RETN",
    "IM 1",
    "IN A,(C)",
    "OUT (C),A",
    "ADC HL,SP",
    "LD SP,(nn)",
    "NEG",
    "RETN",
    "IM 2",
    "LDI",
    "CPI",
    "INI",
    "OUTI",
    "LDD",
    "CPD",
    "IND",
    "OUTD",
    "LDIR",
    "CPIR",
    "INIR",
    "OTIR",
    "LDDR",
    "CPDR",
    "INDR",
    "OTDR"
};

static const char* Z80MNEMONICSDD[]=
{
    "ADD IX,BC",
    "ADD IX,DE",
    "LD IX,nn",
    "LD (nn),IX",
    "INC IX",
    "INC IXH",
    "DEC IXH",
    "LD IXH,n",
    "ADD IX,IX",
    "LD IX,(nn)",
    "DEC IX",
    "INC IXL",
    "DEC IXL",
    "LD IXL,n",
    "INC (IX+d)",
    "DEC (IX+d)",
    "LD (IX+d),n",
    "ADD IX,SP",
    "LD B,IXH",
    "LD B,IXL",
    "LD B,(IX+d)",
    "LD C,IXH",
    "LD C,IXL",
    "LD C,(IX+d)",
    "LD D,IXH",
    "LD D,IXL",
    "LD D,(IX+d)",
    "LD E,IXH",
    "LD E,IXL",
    "LD E,(IX+d)",
    "LD IXH,B",
    "LD IXH,C",
    "LD IXH,D",
    "LD IXH,E",
    "LD IXH,IXH",
    "LD IXH,IXL",
    "LD H,(IX+d)",
    "LD IXH,A",
    "LD IXL,B",
    "LD IXL,C",
    "LD IXL,D",
    "LD IXL,E",
    "LD IXL,IXH",
    "LD IXL,IXL",
    "LD L,(IX+d)",
    "LD IXL,A",
    "LD (IX+d),B",
    "LD (IX+d),C",
    "LD (IX+d),D",
    "LD (IX+d),E",
    "LD (IX+d),H",
    "LD (IX+d),L",
    "LD (IX+d),A",
    "LD A,IXH",
    "LD A,IXL",
    "LD A,(IX+d)",
    "ADD A,IXH",
    "ADD A,IXL",
    "ADD A,(IX+d",
    "ADC A,IXH",
    "ADC A,IXL",
    "ADC A,(IX+d",
    "SUB IXH",
    "SUB IXL",
    "SUB (IX+d)",
    "SBC A,IXH",
    "SBC A,IXL",
    "SBC A,(IX+d",
    "AND IXH",
    "AND IXL",
    "AND (IX+d)",
    "XOR IXH",
    "XOR IXL",
    "XOR (IX+d)",
    "OR IXH",
    "OR IXL",
    "OR (IX+d)",
    "CP IXH",
    "CP IXL",
    "CP (IX+d)",
    "LD B,RLC (IX+d)",
    "LD C,RLC (IX+d)",
    "LD D,RLC (IX+d)",
    "LD E,RLC (IX+d)",
    "LD H,RLC (IX+d)",
    "LD L,RLC (IX+d)",
    "RLC (IX+d)",
    "LD A,RLC (IX+d)",
    "LD B,RRC (IX+d)",
    "LD C,RRC (IX+d)",
    "LD D,RRC (IX+d)",
    "LD E,RRC (IX+d)",
    "LD H,RRC (IX+d)",
    "LD L,RRC (IX+d)",
    "RRC (IX+d)",
    "LD A,RRC (IX+d)",
    "LD B,RL (IX+d)",
    "LD C,RL (IX+d)",
    "LD D,RL (IX+d)",
    "LD E,RL (IX+d)",
    "LD H,RL (IX+d)",
    "LD L,RL (IX+d)",
    "RL (IX+d)",
    "LD A,RL (IX+d)",
    "LD B,RR (IX+d)",
    "LD C,RR (IX+d)",
    "LD D,RR (IX+d)",
    "LD E,RR (IX+d)",
    "LD H,RR (IX+d)",
    "LD L,RR (IX+d)",
    "RR (IX+d)",
    "LD A,RR (IX+d)",
    "LD B,SLA (IX+d)",
    "LD C,SLA (IX+d)",
    "LD D,SLA (IX+d)",
    "LD E,SLA (IX+d)",
    "LD H,SLA (IX+d)",
    "LD L,SLA (IX+d)",
    "SLA (IX+d)",
    "LD A,SLA (IX+d)",
    "LD B,SRA (IX+d)",
    "LD C,SRA (IX+d)",
    "LD D,SRA (IX+d)",
    "LD E,SRA (IX+d)",
    "LD H,SRA (IX+d)",
    "LD L,SRA (IX+d)",
    "SRA (IX+d)",
    "LD A,SRA (IX+d)",
    "LD B,SLL (IX+d)",
    "LD C,SLL (IX+d)",
    "LD D,SLL (IX+d)",
    "LD E,SLL (IX+d)",
    "LD H,SLL (IX+d)",
    "LD L,SLL (IX+d)",
    "SLL (IX+d)",
    "LD A,SLL (IX+d)",
    "LD B,SRL (IX+d)",
    "LD C,SRL (IX+d)",
    "LD D,SRL (IX+d)",
    "LD E,SRL (IX+d)",
    "LD H,SRL (IX+d)",
    "LD L,SRL (IX+d)",
    "SRL (IX+d)",
    "LD A,SRL (IX+d)",
    "BIT 0,(IX+d)",
    "BIT 0,(IX+d)",
    "BIT 0,(IX+d)",
    "BIT 0,(IX+d)",
    "BIT 0,(IX+d)",
    "BIT 0,(IX+d)",
    "BIT 0,(IX+d)",
    "BIT 0,(IX+d)",
    "BIT 1,(IX+d)",
    "BIT 1,(IX+d)",
    "BIT 1,(IX+d)",
    "BIT 1,(IX+d)",
    "BIT 1,(IX+d)",
    "BIT 1,(IX+d)",
    "BIT 1,(IX+d)",
    "BIT 1,(IX+d)",
    "BIT 2,(IX+d)",
    "BIT 2,(IX+d)",
    "BIT 2,(IX+d)",
    "BIT 2,(IX+d)",
    "BIT 2,(IX+d)",
    "BIT 2,(IX+d)",
    "BIT 2,(IX+d)",
    "BIT 2,(IX+d)",
    "BIT 3,(IX+d)",
    "BIT 3,(IX+d)",
    "BIT 3,(IX+d)",
    "BIT 3,(IX+d)",
    "BIT 3,(IX+d)",
    "BIT 3,(IX+d)",
    "BIT 3,(IX+d)",
    "BIT 3,(IX+d)",
    "BIT 4,(IX+d)",
    "BIT 4,(IX+d)",
    "BIT 4,(IX+d)",
    "BIT 4,(IX+d)",
    "BIT 4,(IX+d)",
    "BIT 4,(IX+d)",
    "BIT 4,(IX+d)",
    "BIT 4,(IX+d)",
    "BIT 5,(IX+d)",
    "BIT 5,(IX+d)",
    "BIT 5,(IX+d)",
    "BIT 5,(IX+d)",
    "BIT 5,(IX+d)",
    "BIT 5,(IX+d)",
    "BIT 5,(IX+d)",
    "BIT 5,(IX+d)",
    "BIT 6,(IX+d)",
    "BIT 6,(IX+d)",
    "BIT 6,(IX+d)",
    "BIT 6,(IX+d)",
    "BIT 6,(IX+d)",
    "BIT 6,(IX+d)",
    "BIT 6,(IX+d)",
    "BIT 6,(IX+d)",
    "BIT 7,(IX+d)",
    "BIT 7,(IX+d)",
    "BIT 7,(IX+d)",
    "BIT 7,(IX+d)",
    "BIT 7,(IX+d)",
    "BIT 7,(IX+d)",
    "BIT 7,(IX+d)",
    "BIT 7,(IX+d)",
    "LD B,RES 0,(IX+d)",
    "LD C,RES 0,(IX+d)",
    "LD D,RES 0,(IX+d)",
    "LD E,RES 0,(IX+d)",
    "LD H,RES 0,(IX+d)",
    "LD L,RES 0,(IX+d)",
    "RES 0,(IX+d)",
    "LD A,RES 0,(IX+d)",
    "LD B,RES 1,(IX+d)",
    "LD C,RES 1,(IX+d)",
    "LD D,RES 1,(IX+d)",
    "LD E,RES 1,(IX+d)",
    "LD H,RES 1,(IX+d)",
    "LD L,RES 1,(IX+d)",
    "RES 1,(IX+d)",
    "LD A,RES 1,(IX+d)",
    "LD B,RES 2,(IX+d)",
    "LD C,RES 2,(IX+d)",
    "LD D,RES 2,(IX+d)",
    "LD E,RES 2,(IX+d)",
    "LD H,RES 2,(IX+d)",
    "LD L,RES 2,(IX+d)",
    "RES 2,(IX+d)",
    "LD A,RES 2,(IX+d)",
    "LD B,RES 3,(IX+d)",
    "LD C,RES 3,(IX+d)",
    "LD D,RES 3,(IX+d)",
    "LD E,RES 3,(IX+d)",
    "LD H,RES 3,(IX+d)",
    "LD L,RES 3,(IX+d)",
    "RES 3,(IX+d)",
    "LD A,RES 3,(IX+d)",
    "LD B,RES 4,(IX+d)",
    "LD C,RES 4,(IX+d)",
    "LD D,RES 4,(IX+d)",
    "LD E,RES 4,(IX+d)",
    "LD H,RES 4,(IX+d)",
    "LD L,RES 4,(IX+d)",
    "RES 4,(IX+d)",
    "LD A,RES 4,(IX+d)",
    "LD B,RES 5,(IX+d)",
    "LD C,RES 5,(IX+d)",
    "LD D,RES 5,(IX+d)",
    "LD E,RES 5,(IX+d)",
    "LD H,RES 5,(IX+d)",
    "LD L,RES 5,(IX+d)",
    "RES 5,(IX+d)",
    "LD A,RES 5,(IX+d)",
    "LD B,RES 6,(IX+d)",
    "LD C,RES 6,(IX+d)",
    "LD D,RES 6,(IX+d)",
    "LD E,RES 6,(IX+d)",
    "LD H,RES 6,(IX+d)",
    "LD L,RES 6,(IX+d)",
    "RES 6,(IX+d)",
    "LD A,RES 6,(IX+d)",
    "LD B,RES 7,(IX+d)",
    "LD C,RES 7,(IX+d)",
    "LD D,RES 7,(IX+d)",
    "LD E,RES 7,(IX+d)",
    "LD H,RES 7,(IX+d)",
    "LD L,RES 7,(IX+d)",
    "RES 7,(IX+d)",
    "LD A,RES 7,(IX+d)",
    "LD B,SET 0,(IX+d)",
    "LD C,SET 0,(IX+d)",
    "LD D,SET 0,(IX+d)",
    "LD E,SET 0,(IX+d)",
    "LD H,SET 0,(IX+d)",
    "LD L,SET 0,(IX+d)",
    "SET 0,(IX+d)",
    "LD A,SET 0,(IX+d)",
    "LD B,SET 1,(IX+d)",
    "LD C,SET 1,(IX+d)",
    "LD D,SET 1,(IX+d)",
    "LD E,SET 1,(IX+d)",
    "LD H,SET 1,(IX+d)",
    "LD L,SET 1,(IX+d)",
    "SET 1,(IX+d)",
    "LD A,SET 1,(IX+d)",
    "LD B,SET 2,(IX+d)",
    "LD C,SET 2,(IX+d)",
    "LD D,SET 2,(IX+d)",
    "LD E,SET 2,(IX+d)",
    "LD H,SET 2,(IX+d)",
    "LD L,SET 2,(IX+d)",
    "SET 2,(IX+d)",
    "LD A,SET 2,(IX+d)",
    "LD B,SET 3,(IX+d)",
    "LD C,SET 3,(IX+d)",
    "LD D,SET 3,(IX+d)",
    "LD E,SET 3,(IX+d)",
    "LD H,SET 3,(IX+d)",
    "LD L,SET 3,(IX+d)",
    "SET 3,(IX+d)",
    "LD A,SET 3,(IX+d)",
    "LD B,SET 4,(IX+d)",
    "LD C,SET 4,(IX+d)",
    "LD D,SET 4,(IX+d)",
    "LD E,SET 4,(IX+d)",
    "LD H,SET 4,(IX+d)",
    "LD L,SET 4,(IX+d)",
    "SET 4,(IX+d)",
    "LD A,SET 4,(IX+d)",
    "LD B,SET 5,(IX+d)",
    "LD C,SET 5,(IX+d)",
    "LD D,SET 5,(IX+d)",
    "LD E,SET 5,(IX+d)",
    "LD H,SET 5,(IX+d)",
    "LD L,SET 5,(IX+d)",
    "SET 5,(IX+d)",
    "LD A,SET 5,(IX+d)",
    "LD B,SET 6,(IX+d)",
    "LD C,SET 6,(IX+d)",
    "LD D,SET 6,(IX+d)",
    "LD E,SET 6,(IX+d)",
    "LD H,SET 6,(IX+d)",
    "LD L,SET 6,(IX+d)",
    "SET 6,(IX+d)",
    "LD A,SET 6,(IX+d)",
    "LD B,SET 7,(IX+d)",
    "LD C,SET 7,(IX+d)",
    "LD D,SET 7,(IX+d)",
    "LD E,SET 7,(IX+d)",
    "LD H,SET 7,(IX+d)",
    "LD L,SET 7,(IX+d)",
    "SET 7,(IX+d)",
    "LD A,SET 7,(IX+d)",
    "POP IX",
    "EX (SP),IX",
    "PUSH IX",
    "JP (IX)",
    "LD SP,IX"
};

static const char* Z80MNEMONICSCB[] =
{
    "RLC B",
    "RLC C",
    "RLC D",
    "RLC E",
    "RLC H",
    "RLC L",
    "RLC (HL)",
    "RLC A",
    "RRC B",
    "RRC C",
    "RRC D",
    "RRC E",
    "RRC H",
    "RRC L",
    "RRC (HL)",
    "RRC A",
    "RL B",
    "RL C",
    "RL D",
    "RL E",
    "RL H",
    "RL L",
    "RL (HL)",
    "RL A",
    "RR B",
    "RR C",
    "RR D",
    "RR E",
    "RR H",
    "RR L",
    "RR (HL)",
    "RR A",
    "SLA B",
    "SLA C",
    "SLA D",
    "SLA E",
    "SLA H",
    "SLA L",
    "SLA (HL)",
    "SLA A",
    "SRA B",
    "SRA C",
    "SRA D",
    "SRA E",
    "SRA H",
    "SRA L",
    "SRA (HL)",
    "SRA A",
    "SLL B",
    "SLL C",
    "SLL D",
    "SLL E",
    "SLL H",
    "SLL L",
    "SLL (HL)",
    "SLL A",
    "SRL B",
    "SRL C",
    "SRL D",
    "SRL E",
    "SRL H",
    "SRL L",
    "SRL (HL)",
    "SRL A",
    "BIT 0,B",
    "BIT 0,C",
    "BIT 0,D",
    "BIT 0,E",
    "BIT 0,H",
    "BIT 0,L",
    "BIT 0,(HL)",
    "BIT 0,A",
    "BIT 1,B",
    "BIT 1,C",
    "BIT 1,D",
    "BIT 1,E",
    "BIT 1,H",
    "BIT 1,L",
    "BIT 1,(HL)",
    "BIT 1,A",
    "BIT 2,B",
    "BIT 2,C",
    "BIT 2,D",
    "BIT 2,E",
    "BIT 2,H",
    "BIT 2,L",
    "BIT 2,(HL)",
    "BIT 2,A",
    "BIT 3,B",
    "BIT 3,C",
    "BIT 3,D",
    "BIT 3,E",
    "BIT 3,H",
    "BIT 3,L",
    "BIT 3,(HL)",
    "BIT 3,A",
    "BIT 4,B",
    "BIT 4,C",
    "BIT 4,D",
    "BIT 4,E",
    "BIT 4,H",
    "BIT 4,L",
    "BIT 4,(HL)",
    "BIT 4,A",
    "BIT 5,B",
    "BIT 5,C",
    "BIT 5,D",
    "BIT 5,E",
    "BIT 5,H",
    "BIT 5,L",
    "BIT 5,(HL)",
    "BIT 5,A",
    "BIT 6,B",
    "BIT 6,C",
    "BIT 6,D",
    "BIT 6,E",
    "BIT 6,H",
    "BIT 6,L",
    "BIT 6,(HL)",
    "BIT 6,A",
    "BIT 7,B",
    "BIT 7,C",
    "BIT 7,D",
    "BIT 7,E",
    "BIT 7,H",
    "BIT 7,L",
    "BIT 7,(HL)",
    "BIT 7,A",
    "RES 0,B",
    "RES 0,C",
    "RES 0,D",
    "RES 0,E",
    "RES 0,H",
    "RES 0,L",
    "RES 0,(HL)",
    "RES 0,A",
    "RES 1,B",
    "RES 1,C",
    "RES 1,D",
    "RES 1,E",
    "RES 1,H",
    "RES 1,L",
    "RES 1,(HL)",
    "RES 1,A",
    "RES 2,B",
    "RES 2,C",
    "RES 2,D",
    "RES 2,E",
    "RES 2,H",
    "RES 2,L",
    "RES 2,(HL)",
    "RES 2,A",
    "RES 3,B",
    "RES 3,C",
    "RES 3,D",
    "RES 3,E",
    "RES 3,H",
    "RES 3,L",
    "RES 3,(HL)",
    "RES 3,A",
    "RES 4,B",
    "RES 4,C",
    "RES 4,D",
    "RES 4,E",
    "RES 4,H",
    "RES 4,L",
    "RES 4,(HL)",
    "RES 4,A",
    "RES 5,B",
    "RES 5,C",
    "RES 5,D",
    "RES 5,E",
    "RES 5,H",
    "RES 5,L",
    "RES 5,(HL)",
    "RES 5,A",
    "RES 6,B",
    "RES 6,C",
    "RES 6,D",
    "RES 6,E",
    "RES 6,H",
    "RES 6,L",
    "RES 6,(HL)",
    "RES 6,A",
    "RES 7,B",
    "RES 7,C",
    "RES 7,D",
    "RES 7,E",
    "RES 7,H",
    "RES 7,L",
    "RES 7,(HL)",
    "RES 7,A",
    "SET 0,B",
    "SET 0,C",
    "SET 0,D",
    "SET 0,E",
    "SET 0,H",
    "SET 0,L",
    "SET 0,(HL)",
    "SET 0,A",
    "SET 1,B",
    "SET 1,C",
    "SET 1,D",
    "SET 1,E",
    "SET 1,H",
    "SET 1,L",
    "SET 1,(HL)",
    "SET 1,A",
    "SET 2,B",
    "SET 2,C",
    "SET 2,D",
    "SET 2,E",
    "SET 2,H",
    "SET 2,L",
    "SET 2,(HL)",
    "SET 2,A",
    "SET 3,B",
    "SET 3,C",
    "SET 3,D",
    "SET 3,E",
    "SET 3,H",
    "SET 3,L",
    "SET 3,(HL)",
    "SET 3,A",
    "SET 4,B",
    "SET 4,C",
    "SET 4,D",
    "SET 4,E",
    "SET 4,H",
    "SET 4,L",
    "SET 4,(HL)",
    "SET 4,A",
    "SET 5,B",
    "SET 5,C",
    "SET 5,D",
    "SET 5,E",
    "SET 5,H",
    "SET 5,L",
    "SET 5,(HL)",
    "SET 5,A",
    "SET 6,B",
    "SET 6,C",
    "SET 6,D",
    "SET 6,E",
    "SET 6,H",
    "SET 6,L",
    "SET 6,(HL)",
    "SET 6,A",
    "SET 7,B",
    "SET 7,C",
    "SET 7,D",
    "SET 7,E",
    "SET 7,H",
    "SET 7,L",
    "SET 7,(HL)",
    "SET 7,A"
};

static const char* Z80MNEMONICSSTANDARD[] = 
{
    "NOP",
    "LD BC,nn",
    "LD (BC),A",
    "INC BC",
    "INC B",
    "DEC B",
    "LD B,n",
    "RLCA",
    "EX AF,AF’",
    "ADD HL,BC",
    "LD A,(BC)",
    "DEC BC",
    "INC C",
    "DEC C",
    "LD C,n",
    "RRCA",
    "DJNZ (PC+e)",
    "LD DE,nn",
    "LD (DE),A",
    "INC DE",
    "INC D",
    "DEC D",
    "LD D,n",
    "RLA",
    "JR (PC+e)",
    "ADD HL,DE",
    "LD A,(DE)",
    "DEC DE",
    "INC E",
    "DEC E",
    "LD E,n",
    "RRA",
    "JR NZ,(PC+e)",
    "LD HL,nn",
    "LD (nn),HL",
    "INC HL",
    "INC H",
    "DEC H",
    "LD H,n",
    "DAA",
    "JR Z,(PC+e)",
    "ADD HL,HL",
    "LD HL,(nn)",
    "DEC HL",
    "INC L",
    "DEC L",
    "LD L,n",
    "CPL",
    "JR NC,(PC+e)",
    "LD SP,nn",
    "LD (nn),A",
    "INC SP",
    "INC (HL)",
    "DEC (HL)",
    "LD (HL),n",
    "SCF",
    "JR C,(PC+e)",
    "ADD HL,SP",
    "LD A,(nn)",
    "DEC SP",
    "INC A",
    "DEC A",
    "LD A,n",
    "CCF",
    "LD B,B",
    "LD B,C",
    "LD B,D",
    "LD B,E",
    "LD B,H",
    "LD B,L",
    "LD B,(HL)",
    "LD B,A",
    "LD C,B",
    "LD C,C",
    "LD C,D",
    "LD C,E",
    "LD C,H",
    "LD C,L",
    "LD C,(HL)",
    "LD C,A",
    "LD D,B",
    "LD D,C",
    "LD D,D",
    "LD D,E",
    "LD D,H",
    "LD D,L",
    "LD D,(HL)",
    "LD D,A",
    "LD E,B",
    "LD E,C",
    "LD E,D",
    "LD E,E",
    "LD E,H",
    "LD E,L",
    "LD E,(HL)",
    "LD E,A",
    "LD H,B",
    "LD H,C",
    "LD H,D",
    "LD H,E",
    "LD H,H",
    "LD H,L",
    "LD H,(HL)",
    "LD H,A",
    "LD L,B",
    "LD L,C",
    "LD L,D",
    "LD L,E",
    "LD L,H",
    "LD L,L",
    "LD L,(HL)",
    "LD L,A",
    "LD (HL),B",
    "LD (HL),C",
    "LD (HL),D",
    "LD (HL),E",
    "LD (HL),H",
    "LD (HL),L",
    "HALT",
    "LD (HL),A",
    "LD A,B",
    "LD A,C",
    "LD A,D",
    "LD A,E",
    "LD A,H",
    "LD A,L",
    "LD A,(HL)",
    "LD A,A",
    "ADD A,B",
    "ADD A,C",
    "ADD A,D",
    "ADD A,E",
    "ADD A,H",
    "ADD A,L",
    "ADD A,(HL)",
    "ADD A,A",
    "ADC A,B",
    "ADC A,C",
    "ADC A,D",
    "ADC A,E",
    "ADC A,H",
    "ADC A,L",
    "ADC A,(HL)",
    "ADC A,A",
    "SUB B",
    "SUB C",
    "SUB D",
    "SUB E",
    "SUB H",
    "SUB L",
    "SUB (HL)",
    "SUB A",
    "SBC A,B",
    "SBC A,C",
    "SBC A,D",
    "SBC A,E",
    "SBC A,H",
    "SBC A,L",
    "SBC A,(HL)",
    "SBC A,A",
    "AND B",
    "AND C",
    "AND D",
    "AND E",
    "AND H",
    "AND L",
    "AND (HL)",
    "AND A",
    "XOR B",
    "XOR C",
    "XOR D",
    "XOR E",
    "XOR H",
    "XOR L",
    "XOR (HL)",
    "XOR A",
    "OR B",
    "OR C",
    "OR D",
    "OR E",
    "OR H",
    "OR L",
    "OR (HL)",
    "OR A",
    "CP B",
    "CP C",
    "CP D",
    "CP E",
    "CP H",
    "CP L",
    "CP (HL)",
    "CP A",
    "RET NZ",
    "POP BC",
    "JP NZ,(nn)",
    "JP (nn)",
    "CALL NZ,(nn)",
    "PUSH BC",
    "ADD A,n",
    "RST 0H",
    "RET Z",
    "RET",
    "JP Z,(nn)",
    "CB Instruction",
    "CALL Z,(nn)",
    "CALL (nn)",
    "ADC A,n",
    "RST 8H",
    "RET NC",
    "POP DE",
    "JP NC,(nn)",
    "OUT (n),A",
    "CALL NC,(nn)",
    "PUSH DE",
    "SUB n",
    "RST 10H",
    "RET C",
    "EXX",
    "JP C,(nn)",
    "IN A,(n)",
    "CALL C,(nn)",
    "DD Instruction",
    "SBC A,n",
    "RST 18H",
    "PO",
    "HL",
    "JP PO,(nn)",
    "SP),HL",
    "CALL PO,(nn)",
    "HL",
    "AND n",
    "20H",
    "PE",
    "HL)",
    "JP PE,(nn)",
    "E,HL",
    "CALL PE,(nn)",
    "ED Instruction",
    "XOR n",
    "RST 28H",
    "RET P",
    "POP AF",
    "JP P,(nn)",
    "DI",
    "CALL P,(nn)",
    "PUSH AF",
    "OR n",
    "RST 30H",
    "RET M",
    "LD SP,HL",
    "JP M,(nn)",
    "EI",
    "CALL M,(nn)",
    "FD Instruction",
    "POP IY",
    "EX (SP),IY",
    "PUSH IY",
    "JP (IY)",
    "LD SP,IY",
    "CP n",
    "RST 38H"
};
